name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker compose up
        run: docker compose up -d

      - name: Install dependencies
        run: docker compose exec app yarn

      - name: Lint
        run: docker compose exec app yarn lint

      - name: Test
        run: docker compose exec app yarn test run # single run without watch mode.
